apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybrid-saas.fullname" . }}-web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hybrid-saas.fullname" . }}-web
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
